build: 
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} 
  binary: timenote
  env: 
    - CGO_ENABLED=0 
  goos: 
    - darwin 
    - linux 
    - freebsd 
  goarch: 
    - amd64 
snapshot: 
  name_template: "{{.Commit}}"
nfpm:
  vendor: Sascha Andres
  homepage: https://livingit.de/code/timenote/
  description: timenote is a tool to take notes with timestamps. You can choose between two different backends
  license: Apache 2.0
  formats:
    - deb
